### ISSUE TITLE
Opening Transaction Reporting takes an eternity

### ISSUE THREAD

**Issue by Koal4** [NEXUSe2e/NEXUSe2e#100] opened 2024-03-07 04:11 UTC
Opening Transaction Reporting takes an eternity

We use this application on our work environment. Luckily it hardly needs any maintenance and is pretty stable. Atm we needed to replace a certificate and we notice every time when we open 'Transaction History' to check if every thing went well it takes an eternity to open (like ~5 to 10mins). This makes it hard to troubleshoot a problem. Everything else we open from the UI we get a normal response. As in pages open en we can adjust settings.

Any pointers how we can fix the slowness of the transaction reporting tool?

We still run on 5.7.2, revision: 6cee688, build: 44

Any help/tips are much appreciated, thanks

**Comment by kbarkam** [comment] 2024-03-11 12:54
Performance Issues like that are usually caused by either not enough memory for the application or to many records inthe database.

If you are using a Tomcat Windows Service, the memory settings can be found in the Tomcat Java settings:
<tomcat_directory>\bin\<tomcat_service_name>w.exe
We recommend the "Maximum memory pool" setting to be set so 4096 MB (4 GB), though depending on you Java Version and the amount and size of your messages you might not need that much.  Of course enough memory needs to be available on the server. 

To remove old database logs/messages/etc you can use the "Database Purge" funktion in the "Tools" section of the UI. How much messages you can purge at once depends on your memory settings and database.

**Comment by kbarkam** [comment] 2024-03-19 11:01
Closing this issue since no new comment was added.

**Closed by kbarkam** 2024-03-19 11:01 UTC
